[Interface]
PrivateKey = uO1VDiqcut1rzeodiGcB53QgKdIFSRusmW1nIYO5Hng=
Address = 10.229.52.5/24
DNS = 10.229.52.1

[Peer]
PublicKey = f1Aqr2q35uIGoX070KUC3NWxcDWs5pMgPSdaPvnFCAI=
PresharedKey = n/3lKEbqDTprY6iULHOhsIcggb/h2wHBy9Btz2mZwFE=
Endpoint = :51820
AllowedIPs = 0.0.0.0/0, ::0/0